export const SET_ALL_CHECKLIST="SET_ALL_CHECKLIST";
export const SET_CHECKLIST_NAME="SET_CHECKLIST_NAME";
export const SET_CHECKLIST_MAJORHEAD_ID="SET_CHECKLIST_MAJORHEAD_ID";
export const SET_CHECKLIST_MINORHEAD_ID="SET_CHECKLIST_MINORHEAD_ID";
export const SET_CHECKLIST_CHECKLIST="SET_CHECKLIST_CHECKLIST";
export const RESET_CHECKLIST="RESET_CHECKLIST";
