export const SET_ALL_JOBCARD="SET_ALL_JOBCARD";
export const SET_JOBCARD_CLIENT_ID="SET_JOBCARD_CLIENT_ID";
export const SET_JOBCARD_FIRM_ID="SET_JOBCARD_FIRM_ID";
export const SET_JOBCARD_MAJORHEAD_ID="SET_JOBCARD_MAJORHEAD_ID";
export const SET_JOBCARD_MINORHEAD_ID="SET_JOBCARD_MINORHEAD_ID";
export const SET_JOBCARD_NAME="SET_JOBCARD_NAME";
export const RESET_JOBCARD="RESET_JOBCARD";